sudo: required
services:
  - docker

before_install:
  - docker build -t snigy/docker-react-test -f Dockerfile.dev .

script:
  - docker run -e CI=true snigy/docker-react-test npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-test"
  env: "DockerReactTest-env"
  bucket_name: "elasticbeanstalk-us-east-2-502431811678"
  bucket_path: "docker-react-test"
  on:
    branch: master
  access_key_id : $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"